# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) # This condition ensures the action runs only when the branch is the default branch

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Deploy to Cloudways
      env:
        SERVER_ID: ${{ secrets.SERVER_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        GIT_URL: git@github.com:${{ github.repository_owner }}/${{ github.repository }}.git
        BRANCH_NAME: ${{ github.ref_name }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        API_URL: ${{ secrets.API_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        node run.js $GIT_URL $BRANCH_NAME